### ISSUE TITLE
Error handler

### ISSUE THREAD

**Issue by rolanday** [kmalakoff/walk-filtered#4]
Large directory scans can run into some folders that process does not have permissions tor read, which results in walk aborting before rest of scan completes (for all the other folders it would have otherwise been able to read).

```
(node:13694) UnhandledPromiseRejectionWarning: Error: EPERM: operation not permitted, scandir '/users/roland/Pictures/Photos Library.photoslibrary'
```

Can such errors instead be caught and notified via error handler so rest of scan can complete?

--
Also, minor doc error for callback pattern.

This:
```
walk(rootPath, function(path, callback) { /* do something */ callback(null, true or false); }, {async: true}, done);
```
Should be updated to include stats like so:
```
walk(rootPath, function(path, stats, callback) { /* do something */ callback(null, true or false); }, {async: true}, done);
```

Thanks much!

**Comment by kmalakoff** [comment]
Hi Roland. Thank you for the documentation note (I've updated the docs) and processed your feature request. I added an option called error that you can use to be notified of errors and expected ones ('ENOENT', 'EPERM', 'EACCES', 'ELOOP') will not cause a stop in flow.

Also, I refactored this library into an iteration-style library which you can find here: https://www.npmjs.com/package/fs-iterator

Finally, instead of individual path and stats, now I pass a single object with basename, path, fullPath, and stats.

Let me know if you have any other suggestions!
